Add home and about pages
tugsem/VillageFestival pull request #1
Opened 2022-04-14 10:22 UTC by tugsem

##In this branch I :
- Added home page,
- Added about page,
- Created responsive styles for min: 768px screen sizes,
- Add dynamic featured artists section with a javasript object whicah contains list' data.
-Deploy the page using Github pages.

2022-04-14 19:12 UTC, RolandM99 requested changes
Hi @tugsem , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Instead of adding your presentation video loom link in your PR description, add it in your README file.
- [ ] Make sure that you submit the right link, for now when I click on the submitted link to watch the video, I get an` error 404`. kindly, preview your link before submit it in your readme.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-14 19:12 UTC, RolandM99 commented on index.html
> +</body>
- [ ] **REQUIRED**: Our website should have a partner section and a footer section referencing to the original design here:
![image](https://user-images.githubusercontent.com/71874425/163452311-5682f403-c242-47ed-8f0e-fa627bf36c38.png)
- Kindly, Make sure that you add those two sections and they fit the design guidlines.

2022-04-14 19:12 UTC, RolandM99 commented on index.html
> +</body>
- [ ] **REQUIRED**: Our website should have a partner section and a footer section referencing to the original design here:
![image](https://user-images.githubusercontent.com/71874425/163452311-5682f403-c242-47ed-8f0e-fa627bf36c38.png)
- Kindly, Make sure that you add those two sections and they fit the design guidlines.

2022-04-14 19:12 UTC, RolandM99 commented on script.js
> +    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
- [ ] Good job so far by implementing the artist featured section 🎯 . But, to personalized our website and make it more attractive, It'll be better to replace the placeholder text `lorem ipsum` with the personalized text of your choice(Name, expertise,description,...)

2022-04-14 19:12 UTC, RolandM99 commented on about.html
> +    </section>
- [ ] On this page ( `About page` ), the partner section still being empty. Please, Kindly fill it by adding some partners of your choice icons.
![image](https://user-images.githubusercontent.com/71874425/163455476-8df5b769-aae0-4ed5-8dce-85cdc4cf2fbc.png)

2022-04-14 19:12 UTC, RolandM99 commented on script.js
> +});
- [ ] For mobile version, By Clicking on each link in the navbar menu, the navbar menu should disappear. For now we can observe that just by clicking on the about and home link. please, kindly fix it for other links so that you will improve the UX of our website.

2022-04-14 19:12 UTC, RolandM99 commented on index.html
> +        <div id="cancel">&times;</div>
- [ ] **REQUIRED:** As highlighted in the project requirement, our website should have a top short bar section with social media links, logout, and language links aligned to the right.
### Original design:
![image](https://user-images.githubusercontent.com/71874425/163458898-8cfd18a0-3c8d-4895-b1b7-8e933ab90dff.png)
- So, Kindly implement and add this short dark bar to our website to make it identical to the original design.

2022-04-15 11:31 UTC, Mre55 approved these changes
**Hi @tugsem,** 

# Status: APPROVED  🎉 🎊 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 11:35 UTC, merged